job:  #12003  This will likely get abandoned.  Instead, I will downgrade xtuml/models for now.  But I wanted to keep this commit.

diff --git a/bin/round_trip b/bin/round_trip
--- a/bin/round_trip
+++ b/bin/round_trip
@@ -1,25 +1,26 @@
 #!/bin/bash
-# 
-#  This utility is used to run the full MASL round trip (convert, import,
-#  export, diff) on MASL domains.  The diff report that is produced helps
-#  users validate that the BridgePoint MASL flow works.
+#
+#  This utility is used to run the full round trip (convert, import,
+#  export, diff) on MASL/WASL domains.  The diff report that is produced helps
+#  users validate that the BridgePoint MASL/WASL flow works.
 #
 #  Please note that the BridgePoint CLI Import uses a graphical eclipse workbench which
 #  will capture focus as this script runs.  To run this script completely headlessly,
 #  install the xvfb package for your distribution and call this script using xvfb-run.
 #
-#   ./masl_round_trip -d <domain source directory(s) ...> -p <project soruce directory> [-o <output directory>] [-c]
-#   xvfb-run ./masl_round_trip -d <domain source directory(s) ...> -p <project soruce directory> [-o <output directory>] [-c]
+#   ./round_trip -d <domain source directory(s) ...> -p <project soruce directory> [-o <output directory>] [-a <architecture>] [-c]
+#   xvfb-run ./round_trip -d <domain source directory(s) ...> -p <project soruce directory> [-o <output directory>] [-a <architecture>] [-c]
 
 # USAGE
-print_usage () { 
+print_usage () {
     echo "Usage:"
-    echo "        masl_round_trip -d <domain source directory(s) ...> -p <project soruce directory> [-o <output directory>] [-r] [-c]";
+    echo "        round_trip -d <domain source directory(s) ...> -p <project soruce directory> [-o <output directory>] [-a <architecture>] [-r] [-c]";
     echo " ";
     echo "  - Up to twenty domains may be specified. If a project is specified, only the project is diff'd.";
     echo "  - Consider installing xvfb and calling this script with xvfb-run to execute headlessly. See info in this script's header.";
     echo "  - Specify the '-c' flag to enable and produce code coverage statistics.";
     echo "  - Specify the '-r' flag to force exit and relaunch of BridgePoint before export.";
+    echo "  - Specify '-a <architecture>' to select a specific architecture (WASL) for model testing; MASL is the default.";
     echo -e "\n";
 }
 
@@ -44,11 +45,12 @@ PROJ_DIR=
 OUT_DIR=
 RELAUNCH=
 COVERAGE=
+ARCHITECTURE="MASL" # Default to MASL.
 
 # parse arguments
 DIRECTIVE=
 for arg in $@; do
-    if [[ $arg == "-d" || $arg == "-p" || $arg == "-o" ]]; then     # set the directive
+    if [[ $arg == "-d" || $arg == "-p" || $arg == "-o" || $arg == "-a" ]]; then # set the directive
         DIRECTIVE=$arg
     elif [[ $arg == "-r" ]]; then                                   # relaunch BP before export
         RELAUNCH=$arg
@@ -60,6 +62,8 @@ for arg in $@; do
         PROJ_DIR=$arg
     elif [[ $DIRECTIVE == "-o" && $OUT_DIR == "" ]]; then           # only can set the output directory once
         OUT_DIR=$arg
+    elif [[ $DIRECTIVE == "-a" ]]; then                                   # produce coverage statistics
+        ARCHITECTURE=$arg
     else
         print_usage
         exit 1
@@ -83,13 +87,13 @@ if [[ $OUT_DIR == "" ]]; then OUT_DIR=.; fi
 # make the output directory if there is one
 if [[ $OUT_DIR != "" ]]; then
     if ! mkdir -p $OUT_DIR; then
-        echo "-masl_round_trip: ERROR could not create directory '$OUT_DIR'" 1>&2
+        echo "-round_trip:  ERROR could not create directory '$OUT_DIR'" 1>&2
         exit 1
     fi
 fi
 
 ###########################
-# Setup 
+# Setup
 ###########################
 export WORKSPACE="/tmp/importwork"
 
@@ -109,19 +113,19 @@ CONVERTDIR="/tmp/convertdir"
 for domain in ${DOM_DIRS[*]}; do
     domname=$(basename $domain)
     rm -rf $CONVERTDIR/$domname
-    masl2xtuml -d $domain -o $CONVERTDIR 
+    masl2xtuml -a $ARCHITECTURE -d $domain -o $CONVERTDIR
 done
 # process project
 if [[ $PROJ_DIR != "" ]]; then
   projname=$(basename $PROJ_DIR)
   rm -rf $CONVERTDIR/$projname
-  masl2xtuml -p $PROJ_DIR -o $CONVERTDIR 
+  masl2xtuml -a $ARCHITECTURE -p $PROJ_DIR -o $CONVERTDIR
 fi
 
 ###########################
 # Import, Export, Diff
 ###########################
-MODELOUTDIR="/tmp/maslout"
+MODELOUTDIR="/tmp/modelout"
 
 domNum=0
 for domain in ${DOM_DIRS[*]}; do
@@ -135,7 +139,7 @@ for domain in ${DOM_DIRS[*]}; do
     echo "Round trip is now importing"
     CLI.sh Import -file $CONVERTDIR/$domname/$domname.xtuml -targetProject $domProj -deleteExisting >/tmp/import_log_$domProj.txt 2>&1
     if [[ ! -e $WORKSPACE/$domProj/models/$domProj/types/types.xtuml ]]; then
-      # First import didn't work. Import again. 
+      # First import did not work. Import again.
       echo "Failed to import first time through.  Importing again."
       CLI.sh Import -file $CONVERTDIR/$domname/$domname.xtuml -targetProject $domProj -deleteExisting >>/tmp/import_log_$domProj.txt 2>&1
     fi
@@ -151,11 +155,11 @@ for domain in ${DOM_DIRS[*]}; do
 
     # If there was a project specified, do not export and diff domains
     if [[ $PROJ_DIR == "" ]]; then
-      # The component name (from the .mod file) may not be the same as the domain folder we 
+      # The component name (from the .mod file) may not be the same as the domain folder we
       # used during the processing.  So we calculate it from the .mod file name.
       compfile=$(ls $domain/*.mod)
       compname=$(basename -s .mod $compfile)
-      echo "Converting $compname from xtUML to MASL"
+      echo "Converting $compname from xtUML to" $ARCHITECTURE
       if [[ -d $MODELOUTDIR ]]; then
          rm -rf $MODELOUTDIR
       fi
@@ -164,7 +168,9 @@ for domain in ${DOM_DIRS[*]}; do
       # Copy extra .int files to the output.  Note that we do this _before_ running 
       # xtuml2masl so that xtuml2masl will overwrite the int for the domain being converted,
       # which we want to happen so that we are checking the int created by the x2m process.
-      cp $domain/*.int $MODELOUTDIR/$compname
+      if [[ "MASL" == $ARCHITECTURE ]]; then
+        cp $domain/*.int $MODELOUTDIR/$compname
+      fi
 
       # Optionally relaunch BridgePoint before export
       if [[ $RELAUNCH != "" ]]; then
@@ -172,11 +178,20 @@ for domain in ${DOM_DIRS[*]}; do
         CLI.sh Launch
       fi
 
-      xtuml2masl $COVERAGE -i $WORKSPACE/$domProj/ -d $compname -o $MODELOUTDIR
+      if [[ "WASL" == $ARCHITECTURE ]]; then
+        xtuml2masl $COVERAGE -i $WORKSPACE/$domProj/ -d $compname -o $MODELOUTDIR -a $ARCHITECTURE -xf
+      else
+        xtuml2masl $COVERAGE -i $WORKSPACE/$domProj/ -d $compname -o $MODELOUTDIR -a $ARCHITECTURE
+      fi
 
       # Now diff
       echo "Diff'ing input and output."
-      masldiff $domain $MODELOUTDIR/$compname > $MODELOUTDIR/$compname/diff_report.txt
+      if [[ "WASL" == $ARCHITECTURE ]]; then
+        wasldiff $domain/WASL $MODELOUTDIR/$compname > /tmp/diff_report.txt
+      else
+        masldiff $domain $MODELOUTDIR/$compname > /tmp/diff_report.txt
+      fi
+      mv /tmp/diff_report.txt $MODELOUTDIR/$compname/diff_report.txt
       if [[ -d $OUT_DIR/$compname ]]; then
          rm -rf $OUT_DIR/$compname
       fi
@@ -202,7 +217,7 @@ if [[ $PROJ_DIR != "" ]]; then
     echo "Round trip is now importing"
     CLI.sh Import -file $CONVERTDIR/$projname/$projname.xtuml -targetProject p1 -deleteExisting -allowIPRs >/tmp/import_log_p1.txt 2>&1
     if [[ ! -e $WORKSPACE/p1/models/p1/types/types.xtuml ]]; then
-      # First import didn't work. Import again. 
+      # First import didn't work. Import again.
       echo "Failed to import first time through.  Importing again."
       CLI.sh Import -file $CONVERTDIR/$projname/$projname.xtuml -targetProject p1 -deleteExisting -allowIPRs >>/tmp/import_log_p1.txt 2>&1
     fi
@@ -216,19 +231,21 @@ if [[ $PROJ_DIR != "" ]]; then
         cp $CONVERTDIR/$projname/application.mark $WORKSPACE/p1/gen/
     fi
 
-    # The component name (from the .prj file) may not be the same as the project folder we 
+    # The component name (from the .prj file) may not be the same as the project folder we
     # used during the processing.  So we calculate it from the .prj file name.
     compfile=$(ls $PROJ_DIR/*.prj)
     compname=$(basename -s .prj $compfile)
-    echo "Converting $compname from xtUML to MASL"
+    echo "Converting $compname from xtUML to " $ARCHITECTURE
     if [[ -d $MODELOUTDIR ]]; then
        rm -rf $MODELOUTDIR
     fi
     mkdir -p $MODELOUTDIR/$compname
 
-    # Copy extra INT files from the original source to the MASL output dir 
-    echo "Copying $PROJ_DIR/*.int to $MODELOUTDIR/$compname"
-    cp $PROJ_DIR/*.int $MODELOUTDIR/$compname
+    # Copy extra INT files from the original source to the output dir 
+    if [[ "MASL" == $ARCHITECTURE ]]; then
+      echo "Copying $PROJ_DIR/*.int to $MODELOUTDIR/$compname"
+      cp $PROJ_DIR/*.int $MODELOUTDIR/$compname
+    fi
 
     # Optionally relaunch BridgePoint before export
     if [[ $RELAUNCH != "" ]]; then
@@ -236,11 +253,19 @@ if [[ $PROJ_DIR != "" ]]; then
       CLI.sh Launch
     fi
 
-    xtuml2masl $COVERAGE -P -i $WORKSPACE/p1 -p $compname -o $MODELOUTDIR
+    if [[ "WASL" == $ARCHITECTURE ]]; then
+      xtuml2wasl $COVERAGE -P -i $WORKSPACE/p1 -p $compname -o $MODELOUTDIR -a $ARCHITECTURE -xf
+    else
+      xtuml2masl $COVERAGE -P -i $WORKSPACE/p1 -p $compname -o $MODELOUTDIR -a $ARCHITECTURE
+    fi
 
     # Now diff
     echo "Diff'ing input and output."
-    masldiff $PROJ_DIR $MODELOUTDIR/$compname > $MODELOUTDIR/$compname/diff_report.txt
+    if [[ "WASL" == $ARCHITECTURE ]]; then
+      wasldiff $PROJ_DIR/WASL $MODELOUTDIR/$compname > $MODELOUTDIR/$compname/diff_report.txt
+    else
+      masldiff $PROJ_DIR $MODELOUTDIR/$compname > $MODELOUTDIR/$compname/diff_report.txt
+    fi
     if [[ -d $OUT_DIR/$compname ]]; then
        rm -rf $OUT_DIR/$compname
     fi
@@ -252,7 +277,7 @@ if [[ $PROJ_DIR != "" ]]; then
       if [[ -s $OUT_DIR/$compname/diff_report.txt ]]; then
         echo -e "\nDiff report is in $OUT_DIR/$compname/diff_report.txt"
       else
-        echo -e "\nThe output is identical to the input." 
+        echo -e "\nThe output is identical to the input."
       fi
     fi
 fi
